import { GetServerSideProps, NextPage } from "next";
import Image from "next/image";
import { useState, useEffect } from "react";
import Head from "next/head";
import { fetchVideos, fetchFilmDetails, fetchWatchProviders } from "fetch";
import { BASE_IMG_ORIGINAL } from "globalConst";
import Carousel from "components/Carousel";
import Button from "components/Button";
import SeasonsList from "components/SeasonsList";
import WatchProviders from "components/WatchProviders";
import Link from "next/link";
import { useRouter } from "next/router";
import VideoPlayer from "components/VideoPlayer";
import Credit from "components/Credit";
import Reviews from "components/Reviews";

type TFilm = {
  id: number;
  release_date: string;
  first_air_date: string;
  title: string;
  name: string;
  poster_path: string;
  backdrop_path: string;
  genres: any[];
  overview: any[];
  runtime: number;
  vote_average: number;
  seasons: any[];
};

type TWatchProviders = {
  buy: any[];
  flatrate: any[];
};

type TDetails = {
  film: TFilm;
  videos: any[];
  watchProviders: TWatchProviders;
};

const Details: NextPage<TDetails> = ({ film, videos, watchProviders }) => {
  const {
    id,
    release_date,
    first_air_date,
    title,
    name,
    poster_path,
    backdrop_path,
    genres,
    overview,
    runtime,
    vote_average,
    seasons,
  } = film;

  const [imgAs, setImgAs] = useState("");
  const [video, setVideo] = useState<{ type: string; key: string }>();
  const titleDisplay = title ? title : name;
  let release = "";
  if (release_date) release_date.split("-")[0];
  if (first_air_date) first_air_date.split("-")[0];
  const imgUrl = BASE_IMG_ORIGINAL + imgAs;

  const { buy, flatrate } = watchProviders;
  const router = useRouter();
  const { category } = router.query;
  const { asPath } = router;

  useEffect(() => {
    window.innerWidth < 500 ? setImgAs(poster_path) : setImgAs(backdrop_path);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    const main = document.querySelector("#category-details");
    main?.scrollTo(0, main?.scrollTop);
    if (asPath.split("#play=").length > 0) {
      const videoKey = asPath.split("#play=")[1];
      const videoSelected = videos.filter(
        ({ key }: { key: string }) => key === videoKey
      );
      setVideo(videoSelected[0]);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [asPath]);

  // key trailer
  let keyTrailer = "";
  let i = 0;
  while (i < videos.length) {
    if (videos[i].type === "Trailer") {
      keyTrailer = videos[i].key;
      break;
    }
    i++;
  }

  if (!film) return <div>Data Not Found</div>;

  return (
    <main id="category-details" className="bg-black relative">
      <Head>
        <title> Hilman App | Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-screen relative w-full text-white bg-cover">
        <button
          onClick={() => router.push("/" + category)}
          className="absolute pl-3 md:pl-20 mt-10 top-0 z-30 cursor-pointer flex font-thin items-center gap-2"
        >
          <Image width={10} height={10} src="/icons/arrow-left.svg" alt="" />
          back
        </button>
        <div className="relative w-full h-full">
          {imgAs && (
            <Image
              layout="fill"
              objectFit="cover"
              objectPosition={"center"}
              src={imgUrl}
              alt={titleDisplay}
              quality={100}
              priority
            />
          )}
        </div>
        <span className="absolute h-[300px] bg-gradient-to-t from-black bottom-[-2px] z-10 w-full"></span>
        <div className="absolute left-0 bottom-0 z-20 w-full px-3 lg:px-20 mb-10 lg:mb-20">
          <h1 className="text-[2rem] lg:text-[68px] mb-5 font-bold">
            {titleDisplay}
          </h1>
          <div className="flex items-center gap-2 mb-5 text-sm font-light">
            <span>{vote_average}</span>
            <span className="w-[3px] h-[3px] bg-white rounded-full" />
            <span>{runtime} minutes</span>
            <span className="w-[3px] h-[3px] bg-white rounded-full" />
            <span>{release}</span>
          </div>
          <ul className="flex gap-4 flex-wrap text-sm mb-5">
            {genres.map(({ name }: typeof film, i: number) => {
              return (
                <li
                  key={i}
                  className="backdrop-blur-[1px] whitespace-nowrap bg-opacity-10 bg-white px-3 py-1 flex-items-center rounded-full font-light"
                >
                  {name}
                </li>
              );
            })}
          </ul>
          <p className="tracking-wide max-w-[270px] max-h-[100px] overflow-auto md:max-w-[600px] mb-10 font-thin">
            {overview}
          </p>
          <div className="flex gap-3">
            <Button onClick={() => ""} label="Rate Now" />
            <Button
              onClick={() => {
                if (!keyTrailer) {
                  alert("There is no trailer");
                  return;
                }
                router.push(router.asPath + "#play=" + keyTrailer);
              }}
              variant="secondary"
              label="View Trailer"
            />
          </div>
        </div>
      </section>
      <section className="bg-black text-white w-full pt-20 min-h-screen">
        {videos.length > 0 && (
          <Carousel className="mb-20 px-3 lg:px-20" data={videos} />
        )}
        {seasons && <SeasonsList data={seasons} />}
        <Credit id={id} category={category} />
        <Reviews id={id} category={category} />
        {(buy || flatrate) && (
          <WatchProviders title="Watch Providers" data={buy ? buy : flatrate} />
        )}
      </section>
      {video && <VideoPlayer data={video} />}
    </main>
  );
};

export const getServerSideProps: GetServerSideProps<TDetails> = async (ctx) => {
  const { category, id } = ctx.query;
  type CategoryId = typeof category & typeof id;
  const film = await fetchFilmDetails<CategoryId>(category, id);
  const videos = await fetchVideos<CategoryId>(category, id);
  const watchProviders = await fetchWatchProviders<CategoryId>(category, id);

  return {
    props: {
      film: film ? film : [],
      videos: videos ? videos : [],
      watchProviders: watchProviders ? watchProviders : [],
    },
  };
};

export default Details;
