import { fetchPersonDetails } from "fetch/fetchPersonDetails";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { BASE_IMG_ORIGINAL } from "globalConst";

type TDetails = {
  person: {
    name: string;
    profile_path: string;
    biography: string;
    also_known_as: any[];
  };
};

const Details: NextPage<TDetails> = ({ person }) => {
  const { name, profile_path, biography } = person;
  const as = person.also_known_as;
  return (
    <main className="bg-black h-full overflow-y-auto text-white">
      <Head>
        <title>Hilman App | {person.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className="fixed w-full h-screen">
        <span className="absolute w-[200px] h-[200px] bottom-0 bg-black-500 right-0 blur-3xl opacity-10"></span>
        <span className="absolute w-[150px] h-[150px] bottom-0 bg-red left-0 blur-3xl opacity-20"></span>
        <span className="absolute w-[150px] h-[150px] top-40 bg-red right-0 blur-3xl opacity-20"></span>
      </span>
      <section className="container px-3 md:px-0 mx-auto pt-[100px] min-h-screen w-full">
        <div className="flex gap-5">
          <picture className="shrink-0 relative aspect-[2/3] w-[300px] h-full bg-black-500 rounded-[10px]">
            <Image
              className="rounded-[10px]"
              layout="fill"
              src={BASE_IMG_ORIGINAL + profile_path}
              alt=""
            />
          </picture>
          <div>
            <h1 className="text-5xl font-bold mb-6">{name}</h1>
            <h5 className="mb-3">Also known as:</h5>
            <ul className="flex gap-4 flex-wrap mb-6">
              {as.map((as_name, i) => {
                return (
                  <li
                    key={i}
                    className="bg-white bg-opacity-10 px-5 rounded-full whitespace-nowrap"
                  >
                    {as_name}
                  </li>
                );
              })}
            </ul>
            <p className="font-thin opacity-80">{biography}</p>
          </div>
        </div>
      </section>
    </main>
  );
};

export const getServerSideProps: GetServerSideProps<TDetails> = async (ctx) => {
  let { id } = ctx.query;
  const results = await fetchPersonDetails<typeof id>(id);

  return {
    props: {
      person: results,
    },
  };
};

export default Details;
