import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useUpdateAge } from "../context/hooks/useUpdateAge";

const Home: NextPage = () => {
  const { age, updateAge } = useUpdateAge();
  return (
    <div>
      <Head>
        <title>Hilman App | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button
        className="bg-blue-500 px-2 py-2 rounded-md"
        onClick={() => updateAge(10)}
      >
        AGE : {age}
      </button>
      <Link href="/category">To category</Link>
    </div>
  );
};

export default Home;
