import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useUpdateAge } from "./_app";
import Link from "next/link";

const Home: NextPage = () => {
  const { state, updateAge } = useUpdateAge();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={updateAge}>AGE : {state.age}</button>
      <Link href="/category">To category</Link>
    </div>
  );
};

export default Home;
